import app from "./app";
import "./database";
// import axios from "axios"

app.listen(app.get("port"));

console.log(`Server is running on port ${app.get("port")}`);

// let productos = [{nombre:"DP Tajada Piña",presentacion:"Unidad",codigo:"1000001",marca:"Doña Pepa",precioUnitario:1.5,habilitado:0},
// {nombre:"DP Tradicional",presentacion:"1/2 kg",codigo:"1000002",marca:"Doña Pepa",precioUnitario:7,habilitado:1},
// {nombre:"DP Tradicional",presentacion:"1/4 kg - 250 g",codigo:"1000003",marca:"Doña Pepa",precioUnitario:3.5,habilitado:1},
// {nombre:"DP Exportación",presentacion:"1 kg",codigo:"1000004",marca:"Doña Pepa",precioUnitario:20,habilitado:1},
// {nombre:"DP Exportación",presentacion:"1/2 kg",codigo:"1000005",marca:"Doña Pepa",precioUnitario:10,habilitado:1},
// {nombre:"DP Exportación",presentacion:"1/4 kg - 250 g",codigo:"1000006",marca:"Doña Pepa",precioUnitario:5,habilitado:1},
// {nombre:"DP Exportación",presentacion:"1/8 kg - 125 g",codigo:"1000007",marca:"Doña Pepa",precioUnitario:3,habilitado:1},
// {nombre:"DP Especial",presentacion:"1 kg",codigo:"1000008",marca:"Doña Pepa",precioUnitario:14,habilitado:1},
// {nombre:"DP Especial",presentacion:"1/2 kg",codigo:"1000009",marca:"Doña Pepa",precioUnitario:7,habilitado:1},
// {nombre:"LB Tajada Piña",presentacion:"Unidad",codigo:"1000010",marca:"Lambayecano",precioUnitario:1.5,habilitado:1},
// {nombre:"LB Tajada Manjar",presentacion:"Unidad",codigo:"1000011",marca:"Lambayecano",precioUnitario:2,habilitado:1},
// {nombre:"IB Turrón Iberica",presentacion:"12 unidades",codigo:"1000012",marca:"Iberica",precioUnitario:58,habilitado:1},
// {nombre:"IB Turrón Iberida",presentacion:"Unidad",codigo:"1000013",marca:"Iberica",precioUnitario:5,habilitado:1},
// {nombre:"DP Chocotejas",presentacion:"Unidad",codigo:"1000014",marca:"Doña Pepa",precioUnitario:2,habilitado:1},
// {nombre:"BR Alfajores Vaquita",presentacion:"Unidad",codigo:"1000015",marca:"Bruning",precioUnitario:1.5,habilitado:1},
// {nombre:"ST Natilla",presentacion:"Unidad",codigo:"1000016",marca:"Lambayecano",precioUnitario:12,habilitado:1},
// {nombre:"SR galletas Paciencia",presentacion:"50 g",codigo:"1000017",marca:"San Roque",precioUnitario:4,habilitado:1},
// {nombre:"SR Chocotejas Pecana",presentacion:"6 unidades",codigo:"1000018",marca:"San Roque",precioUnitario:20,habilitado:1},
// {nombre:"SR Chocotejas Mixtas",presentacion:"6 unidades",codigo:"1000019",marca:"San Roque",precioUnitario:20,habilitado:1},
// {nombre:"SR Alfajores",presentacion:"15 unidades",codigo:"1000020",marca:"San Roque",precioUnitario:16,habilitado:1},
// {nombre:"SR Bolicocos",presentacion:"Unidad",codigo:"1000021",marca:"San Roque",precioUnitario:12,habilitado:1},
// {nombre:"SR Suspiritos",presentacion:"Unidad",codigo:"1000022",marca:"San Roque",precioUnitario:12,habilitado:1},
// {nombre:"SR Natilla",presentacion:"Unidad",codigo:"1000023",marca:"San Roque",precioUnitario:16,habilitado:1},
// {nombre:"SR Antojito",presentacion:"12 unidades",codigo:"1000024",marca:"San Roque",precioUnitario:30,habilitado:1},
// {nombre:"SR Antojito",presentacion:"Unidad",codigo:"1000025",marca:"San Roque",precioUnitario:2.5,habilitado:1},
// {nombre:"SR Redondito",presentacion:"6 unidades",codigo:"1000026",marca:"San Roque",precioUnitario:24,habilitado:1},
// {nombre:"SR Redondito",presentacion:"Unidad",codigo:"1000027",marca:"San Roque",precioUnitario:4,habilitado:1},
// {nombre:"SR Combo Surtido",presentacion:"Unidad",codigo:"1000028",marca:"San Roque",precioUnitario:30,habilitado:1},
// {nombre:"SR Doy Pack Manjar Blanco",presentacion:"Unidad",codigo:"1000029",marca:"San Roque",precioUnitario:10,habilitado:1},
// {nombre:"SR Doy Pack Chirimoya",presentacion:"Unidad",codigo:"1000030",marca:"San Roque",precioUnitario:10,habilitado:1},
// {nombre:"IB Toffees Surtidos",presentacion:"100 g",codigo:"1000031",marca:"Iberica",precioUnitario:7.8,habilitado:1},
// {nombre:"IB Toffees Surtidos",presentacion:"150 g",codigo:"1000032",marca:"Iberica",precioUnitario:10.2,habilitado:1},
// {nombre:"IB Toffees Surtidos",presentacion:"300 g",codigo:"1000033",marca:"Iberica",precioUnitario:17.2,habilitado:1},
// {nombre:"IB Toffees Surtidos",presentacion:"500 g",codigo:"1000034",marca:"Iberica",precioUnitario:26.2,habilitado:1},
// {nombre:"IB Toffees",presentacion:"Unidad",codigo:"1000035",marca:"Iberica",precioUnitario:0.7,habilitado:1},
// {nombre:"IB Bombones Surtido",presentacion:"100 g",codigo:"1000036",marca:"Iberica",precioUnitario:12.5,habilitado:1},
// {nombre:"IB Bombones Surtido",presentacion:"150 g",codigo:"1000037",marca:"Iberica",precioUnitario:17.5,habilitado:1},
// {nombre:"IB Bombones Surtido",presentacion:"300 g",codigo:"1000038",marca:"Iberica",precioUnitario:32,habilitado:1},
// {nombre:"IB Bombones Surtido",presentacion:"500 g",codigo:"1000039",marca:"Iberica",precioUnitario:48.5,habilitado:1},
// {nombre:"IB Bombones",presentacion:"Unidad",codigo:"1000040",marca:"Iberica",precioUnitario:1.2,habilitado:1},
// {nombre:"IB Pastillas de Leche",presentacion:"100 g",codigo:"1000041",marca:"Iberica",precioUnitario:12,habilitado:1},
// {nombre:"IB Pastillas de Leche",presentacion:"150 g",codigo:"1000042",marca:"Iberica",precioUnitario:15,habilitado:1},
// {nombre:"IB Pastillas de Leche",presentacion:"300 g",codigo:"1000043",marca:"Iberica",precioUnitario:24.4,habilitado:1},
// {nombre:"IB Pastillas de Leche",presentacion:"500 g",codigo:"1000044",marca:"Iberica",precioUnitario:40,habilitado:1},
// {nombre:"IB Pastillas Fondant",presentacion:"100 g",codigo:"1000045",marca:"Iberica",precioUnitario:12,habilitado:1},
// {nombre:"IB Pastillas Fondant",presentacion:"150 g",codigo:"1000046",marca:"Iberica",precioUnitario:15,habilitado:1},
// {nombre:"IB Pastillas Fondant",presentacion:"300 g",codigo:"1000047",marca:"Iberica",precioUnitario:24.5,habilitado:1},
// {nombre:"IB Pastillas Fondant",presentacion:"500 g",codigo:"1000048",marca:"Iberica",precioUnitario:40,habilitado:1},
// {nombre:"IB Pastillas",presentacion:"Unidad",codigo:"1000049",marca:"Iberica",precioUnitario:0.7,habilitado:1},
// {nombre:"IB Barra Milky",presentacion:"10 unidades",codigo:"1000050",marca:"Iberica",precioUnitario:43,habilitado:1},
// {nombre:"IB Barra Milky",presentacion:"Unidad",codigo:"1000051",marca:"Iberica",precioUnitario:4.5,habilitado:1},
// {nombre:"IB Barra Mini Milky",presentacion:"10 unidades",codigo:"1000052",marca:"Iberica",precioUnitario:23,habilitado:1},
// {nombre:"IB Barra Mini Milky",presentacion:"20 unidades",codigo:"1000053",marca:"Iberica",precioUnitario:46,habilitado:1},
// {nombre:"IB Barra Mini Milky",presentacion:"Unidad",codigo:"1000054",marca:"Iberica",precioUnitario:2.5,habilitado:1},
// {nombre:"IB Barra Milky S/A",presentacion:"10 unidades",codigo:"1000055",marca:"Iberica",precioUnitario:58,habilitado:1},
// {nombre:"IB Barra Milky S/A",presentacion:"Unidad",codigo:"1000056",marca:"Iberica",precioUnitario:6,habilitado:1},
// {nombre:"IB Barra Mini Milky S/A",presentacion:"10 unidades",codigo:"1000057",marca:"Iberica",precioUnitario:28,habilitado:1},
// {nombre:"IB Barra Mini Milky S/A",presentacion:"20 unidades",codigo:"1000058",marca:"Iberica",precioUnitario:56,habilitado:1},
// {nombre:"IB Barra Mini Milky S/A",presentacion:"Unidad",codigo:"1000059",marca:"Iberica",precioUnitario:3,habilitado:1},
// {nombre:"IB Barra Fondy",presentacion:"10 unidades",codigo:"1000060",marca:"Iberica",precioUnitario:43,habilitado:1},
// {nombre:"IB Barra Fondy",presentacion:"Unidad",codigo:"1000062",marca:"Iberica",precioUnitario:4.5,habilitado:1},
// {nombre:"IB Barra Mini Fondy",presentacion:"10 unidades",codigo:"1000062",marca:"Iberica",precioUnitario:23,habilitado:1},
// {nombre:"IB Barra Mini Fondy",presentacion:"20 unidades",codigo:"1000063",marca:"Iberica",precioUnitario:46,habilitado:1},
// {nombre:"IB Barra Mini Fondy",presentacion:"Unidad",codigo:"1000064",marca:"Iberica",precioUnitario:2.5,habilitado:1},
// {nombre:"IB Barra Fondy S/A",presentacion:"10 unidades",codigo:"1000065",marca:"Iberica",precioUnitario:58,habilitado:1},
// {nombre:"IB Barra Fondy S/A",presentacion:"Unidad",codigo:"1000066",marca:"Iberica",precioUnitario:6,habilitado:1},
// {nombre:"IB Barra Mini Fondy S/A",presentacion:"10 unidades",codigo:"1000067",marca:"Iberica",precioUnitario:28,habilitado:1},
// {nombre:"IB Barra Mini Fondy S/A",presentacion:"20 unidades",codigo:"1000068",marca:"Iberica",precioUnitario:56,habilitado:1},
// {nombre:"IB Barra Mini Fondy S/A",presentacion:"Unidad",codigo:"1000069",marca:"Iberica",precioUnitario:3,habilitado:1},
// {nombre:"IB Corazón",presentacion:"35 g",codigo:"1000070",marca:"Iberica",precioUnitario:6.5,habilitado:1},
// {nombre:"IB Corazón",presentacion:"80 g",codigo:"1000071",marca:"Iberica",precioUnitario:12,habilitado:1},
// {nombre:"IB Corazón",presentacion:"140 g",codigo:"1000072",marca:"Iberica",precioUnitario:23,habilitado:1},
// {nombre:"IB Corazón",presentacion:"180 g",codigo:"1000073",marca:"Iberica",precioUnitario:21,habilitado:1},
// {nombre:"IB Pastillas Surtidas",presentacion:"180 g",codigo:"1000074",marca:"Iberica",precioUnitario:23,habilitado:1},
// {nombre:"IB Bombones Selectos",presentacion:"170 g",codigo:"1000075",marca:"Iberica",precioUnitario:28,habilitado:1},
// {nombre:"IB Dulce Armon¡a",presentacion:"300 g",codigo:"1000076",marca:"Iberica",precioUnitario:38,habilitado:1},
// {nombre:"ST Madera gande",presentacion:"Unidad",codigo:"1000077",marca:"Santo Domingo",precioUnitario:9,habilitado:1},
// {nombre:"ST Madera Chica",presentacion:"Unidad",codigo:"1000078",marca:"Santo Domingo",precioUnitario:7,habilitado:1},
// {nombre:"LB guindon",presentacion:"1 kg",codigo:"1000079",marca:"Lambayecano",precioUnitario:18,habilitado:1},
// {nombre:"LB Pasas",presentacion:"600 g",codigo:"1000080",marca:"Lambayecano",precioUnitario:12,habilitado:1},
// {nombre:"LB Fiorellas",presentacion:"450 g",codigo:"1000081",marca:"Lambayecano",precioUnitario:10,habilitado:1},
// {nombre:"LB Mini Todino",presentacion:"220 g",codigo:"1000082",marca:"Lambayecano",precioUnitario:6,habilitado:1},
// {nombre:"LB Rojo gande",presentacion:"1 kg",codigo:"1000083",marca:"Lambayecano",precioUnitario:25,habilitado:1},
// {nombre:"LB Rojo Chico",presentacion:"600 g",codigo:"1000084",marca:"Lambayecano",precioUnitario:16,habilitado:1},
// {nombre:"LB Azul gande",presentacion:"1 kg",codigo:"1000085",marca:"Lambayecano",precioUnitario:24,habilitado:1},
// {nombre:"LB Azul Chico",presentacion:"600 g",codigo:"1000086",marca:"Lambayecano",precioUnitario:16,habilitado:1},
// {nombre:"LB Redondo",presentacion:"1 kg",codigo:"1000087",marca:"Bruning",precioUnitario:12,habilitado:1},
// {nombre:"TR Rojo",presentacion:"900 g",codigo:"1000088",marca:"Tradición Lambayecana",precioUnitario:25,habilitado:1},
// {nombre:"TR Azul",presentacion:"900 g",codigo:"1000089",marca:"Tradición Lambayecana",precioUnitario:25,habilitado:1},
// {nombre:"TR Porción Rojo",presentacion:"75 g",codigo:"1000090",marca:"Tradición Lambayecana",precioUnitario:2.5,habilitado:1},
// {nombre:"TR Porción Azul",presentacion:"75 g",codigo:"1000091",marca:"Tradición Lambayecana",precioUnitario:2.5,habilitado:1},
// {nombre:"SR Barra Roja",presentacion:"230 g",codigo:"1000092",marca:"San Roque",precioUnitario:20,habilitado:1},
// {nombre:"SR Barra Chirimoya",presentacion:"230 g",codigo:"1000093",marca:"San Roque",precioUnitario:20,habilitado:1},
// {nombre:"SR Barra Lucuma",presentacion:"230 g",codigo:"1000094",marca:"San Roque",precioUnitario:20,habilitado:1},
// {nombre:"SR Barra Frutos Rojos",presentacion:"230 g",codigo:"1000095",marca:"San Roque",precioUnitario:20,habilitado:1},
// {nombre:"Sr Barra Maracuya",presentacion:"230 g",codigo:"1000096",marca:"San Roque",precioUnitario:20,habilitado:1},
// {nombre:"SR Rojo gande",presentacion:"900 g",codigo:"1000097",marca:"San Roque",precioUnitario:40,habilitado:1},
// {nombre:"SR Naranja gande",presentacion:"900 g",codigo:"1000098",marca:"San Roque",precioUnitario:35,habilitado:1},
// {nombre:"SR Azul gande",presentacion:"900 g",codigo:"1000099",marca:"San Roque",precioUnitario:35,habilitado:1},
// {nombre:"SR Rojo Chico",presentacion:"450 g",codigo:"1000100",marca:"San Roque",precioUnitario:25,habilitado:1},
// {nombre:"SR Naranja Chico",presentacion:"450 g",codigo:"1000101",marca:"San Roque",precioUnitario:25,habilitado:1},
// {nombre:"SR Azul Chico",presentacion:"450 g",codigo:"1000102",marca:"San Roque",precioUnitario:25,habilitado:1},
// {nombre:"SR Porción Rojo",presentacion:"75 g",codigo:"1000103",marca:"San Roque",precioUnitario:5,habilitado:1},
// {nombre:"SR Porción Naranja",presentacion:"75 g",codigo:"1000104",marca:"San Roque",precioUnitario:5,habilitado:1},
// {nombre:"SR Porción Azul",presentacion:"75 g",codigo:"1000105",marca:"San Roque",precioUnitario:5,habilitado:1},
// {nombre:"SR Porción Chimiroya",presentacion:"75 g",codigo:"1000106",marca:"San Roque",precioUnitario:5,habilitado:1},
// {nombre:"SR Porción Lucuma",presentacion:"75 g",codigo:"1000107",marca:"San Roque",precioUnitario:5,habilitado:1},
// {nombre:"SR Porción Maracuya",presentacion:"75 g",codigo:"1000108",marca:"San Roque",precioUnitario:5,habilitado:1},
// {nombre:"LB Tajada 3 sabores",presentacion:"Unidad",codigo:"1000109",marca:"Lambayecano",precioUnitario:2,habilitado:1},
// {nombre:"DP Tradicional",presentacion:"1 kg",codigo:"1000001",marca:"Doña Pepa",precioUnitario:14,habilitado:1},
// {nombre:"Panetón Donofrio Bolsa",presentacion:"Unidad",codigo:"1000110",marca:"marca",precioUnitario:22,habilitado:1},
// {nombre:"Panetón Donofrio Caja",presentacion:"Unidad",codigo:"1000111",marca:"marca",precioUnitario:24,habilitado:1},
// {nombre:"Panetón Todino",presentacion:"Unidad",codigo:"1000112",marca:"marca",precioUnitario:22.5,habilitado:1},
// {nombre:"DP Sellado",presentacion:"Unidad",codigo:"1000113",marca:"",precioUnitario:17,habilitado:1},
// {nombre:"Panet¢n Chocot¢n",presentacion:"Unidad",codigo:"1000114",marca:"",precioUnitario:17,habilitado:1},
// {nombre:"SR Porción Frutos Rojos",presentacion:"75 g",codigo:"1000115",marca:"",precioUnitario:5,habilitado:1},
// {nombre:"Karla",presentacion:"Unidad",codigo:"1000116",marca:"",precioUnitario:12.12,habilitado:0},
// {nombre:"fanta naranja",presentacion:"Unidad",codigo:"1000117",marca:"",precioUnitario:4,habilitado:0},
// {nombre:"Fanta Naranja",presentacion:"Unidad",codigo:"1000118",marca:"",precioUnitario:4,habilitado:1},
// {nombre:"Coca Cola",presentacion:"(500ml) 12 unidades",codigo:"1000119",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"coca cola",presentacion:"(500ml) 12 unidades",codigo:"1000120",marca:"",precioUnitario:2.5,habilitado:0},
// {nombre:"Inca Kola",presentacion:"(410ml) 12 unidades",codigo:"1000121",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"Inca kola",presentacion:"(410ml) 12 unidades",codigo:"1000122",marca:"",precioUnitario:2.5,habilitado:0},
// {nombre:"Fanta Kola In glesa",presentacion:"12 unidades",codigo:"1000123",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"Fanta kola in glesa",presentacion:"12 unidades",codigo:"1000124",marca:"",precioUnitario:2,habilitado:0},
// {nombre:"A gua Cielo S/ g",presentacion:"(625 ml) 15 unidades",codigo:"1000125",marca:"",precioUnitario:1.5,habilitado:1},
// {nombre:"A gua San Mateo",presentacion:"(600ml) 15 unidades",codigo:"1000126",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"Sporade Tropical",presentacion:"12 unidades",codigo:"1000127",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"A gua Cielo Chupón",presentacion:"Unidad",codigo:"1000128",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"Coca Cola cero",presentacion:"500ml",codigo:"1000129",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"Inca kola cero",presentacion:"500ml",codigo:"1000130",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"Inca kola Mini",presentacion:"Unidad",codigo:"1000131",marca:"",precioUnitario:1.5,habilitado:1},
// {nombre:"Inca cola mini",presentacion:"Unidad",codigo:"1000132",marca:"",precioUnitario:1.5,habilitado:0},
// {nombre:"Coca Cola Mini",presentacion:"Unidad",codigo:"1000133",marca:"",precioUnitario:1.5,habilitado:1},
// {nombre:"Churro",presentacion:"Unidad",codigo:"1000134",marca:"",precioUnitario:1.5,habilitado:1},
// {nombre:"Tajadas san roques",presentacion:"Unidad",codigo:"1000135",marca:"",precioUnitario:3,habilitado:1},
// {nombre:"Sr alfajor",presentacion:"Unidad",codigo:"1000136",marca:"",precioUnitario:1,habilitado:1},
// {nombre:"Ib tableta de chocolate blanco",presentacion:"40 g",codigo:"1000137",marca:"",precioUnitario:4.8,habilitado:1},
// {nombre:"Bombón de mazap n",presentacion:"Unidad",codigo:"1000138",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"guarana",presentacion:"500 ml",codigo:"1000139",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"Pepsi",presentacion:"500 ml",codigo:"1000140",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"Sprite",presentacion:"500 ml",codigo:"1000141",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"Frugo",presentacion:"Unidad",codigo:"1000142",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"A gua San Luis s/ g",presentacion:"625 ml",codigo:"1000143",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"Fru gos Botella",presentacion:"296ml",codigo:"1000144",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"Volt Azul",presentacion:"300ml",codigo:"1000145",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"A gua San Luis Chupon",presentacion:"Unidad",codigo:"1000146",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"Panetón Metro",presentacion:"Unidad",codigo:"1000147",marca:"",precioUnitario:9.5,habilitado:1},
// {nombre:"IB Tabletas castaña",presentacion:"40 g",codigo:"1000148",marca:"",precioUnitario:4.6,habilitado:1},
// {nombre:"IB Tabletas fondant",presentacion:"40 g",codigo:"1000149",marca:"",precioUnitario:4.6,habilitado:1},
// {nombre:"DP Turrón especial de Chocolate",presentacion:"Unidad",codigo:"1000150",marca:"",precioUnitario:25,habilitado:1},
// {nombre:"Porcion de churros",presentacion:"Unidad",codigo:"1000151",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"Panetón Baldaracci",presentacion:"Unidad",codigo:"1000152",marca:"",precioUnitario:10,habilitado:1},
// {nombre:"Panetón buon natale",presentacion:"Unidad",codigo:"1000154",marca:"",precioUnitario:18,habilitado:1},
// {nombre:"san mateo sin gas",presentacion:"Unidad",codigo:"1000155",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"free tea clasico",presentacion:"Unidad",codigo:"1000156",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"acuñas",presentacion:"Unidad",codigo:"1000157",marca:"",precioUnitario:2,habilitado:1},
// {nombre:"free tea",presentacion:"Unidad",codigo:"1000158",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"chocolate kisses",presentacion:"Unidad",codigo:"1000159",marca:"",precioUnitario:10,habilitado:1},
// {nombre:"bombones ferrero rocher",presentacion:"100 g",codigo:"1000160",marca:"",precioUnitario:25,habilitado:1},
// {nombre:"barra chocolates tottus",presentacion:"Unidad",codigo:"1000161",marca:"",precioUnitario:9,habilitado:1},
// {nombre:"tornado chocolate",presentacion:"Unidad",codigo:"1000162",marca:"",precioUnitario:8,habilitado:1},
// {nombre:"Lb combo familiar",presentacion:"Unidad",codigo:"1000163",marca:"",precioUnitario:25,habilitado:1},
// {nombre:"bizcochos",presentacion:"Unidad",codigo:"1000164",marca:"",precioUnitario:3.5,habilitado:1},
// {nombre:"kekitos",presentacion:"12 unidades",codigo:"1000165",marca:"",precioUnitario:6.5,habilitado:1},
// {nombre:"keke marmoleado",presentacion:"Unidad",codigo:"1000166",marca:"",precioUnitario:10,habilitado:1},
// {nombre:"keke vainilla",presentacion:"Unidad",codigo:"1000167",marca:"",precioUnitario:10,habilitado:1},
// {nombre:"pan de manteca",presentacion:"24 unidades",codigo:"1000168",marca:"",precioUnitario:3.5,habilitado:1},
// {nombre:"pan de yema",presentacion:"24 unidades",codigo:"1000169",marca:"",precioUnitario:3.5,habilitado:1},
// {nombre:"tajadas",presentacion:"10 unidades",codigo:"1000170",marca:"",precioUnitario:10,habilitado:1},
// {nombre:"mini keke",presentacion:"Unidad",codigo:"1000171",marca:"",precioUnitario:7,habilitado:1},
// {nombre:"oreja",presentacion:"Unidad",codigo:"1000172",marca:"",precioUnitario:6,habilitado:1},
// {nombre:"tostadas",presentacion:"Unidad",codigo:"1000173",marca:"",precioUnitario:6,habilitado:1},
// {nombre:"pan de molde",presentacion:"Unidad",codigo:"1000174",marca:"",precioUnitario:4.5,habilitado:1},
// {nombre:"pionono",presentacion:"Unidad",codigo:"1000175",marca:"",precioUnitario:6,habilitado:1},
// {nombre:"miloja",presentacion:"Unidad",codigo:"1000176",marca:"",precioUnitario:6,habilitado:1},
// {nombre:"cachitos de manjar",presentacion:"Unidad",codigo:"1000177",marca:"",precioUnitario:6,habilitado:1},
// {nombre:"taper de tajada",presentacion:"10 unidades",codigo:"1000178",marca:"",precioUnitario:10,habilitado:1},
// {nombre:"tajadas de Panetón",presentacion:"Unidad",codigo:"1000179",marca:"",precioUnitario:1.5,habilitado:1},
// {nombre:"keke chocolate",presentacion:"Unidad",codigo:"1000180",marca:"",precioUnitario:10,habilitado:1},
// {nombre:"LB NARANJA gANDE",presentacion:"1 kg",codigo:"1000181",marca:"",precioUnitario:24,habilitado:1},
// {nombre:"SR miel de abeja",presentacion:"500 g",codigo:"1000182",marca:"",precioUnitario:25,habilitado:1},
// {nombre:"SR al garrobina",presentacion:"480 g",codigo:"1000183",marca:"",precioUnitario:25,habilitado:1},
// {nombre:"SR chifles norteñisimo",presentacion:"Unidad",codigo:"1000184",marca:"",precioUnitario:10,habilitado:1},
// {nombre:"LB Naranja chico",presentacion:"600 g",codigo:"1000185",marca:"",precioUnitario:16,habilitado:1},
// {nombre:"LB dulce de membrillo",presentacion:"Unidad",codigo:"1000186",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"TR Tradicion rojo",presentacion:"450 g",codigo:"1000187",marca:"",precioUnitario:17,habilitado:1},
// {nombre:"TR Tradicion azul",presentacion:"450 g",codigo:"1000188",marca:"",precioUnitario:17,habilitado:1},
// {nombre:"LB dulce de membrillo",presentacion:"Unidad",codigo:"1000189",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"DP Tradicional",presentacion:"1/8 kg - 125 g",codigo:"1000191",marca:"",precioUnitario:2.5,habilitado:1},
// {nombre:"LB PORCION DE MANJAR",presentacion:"75 g",codigo:"1000192",marca:"",precioUnitario:3,habilitado:1},
// {nombre:"LB PORCION 2 SABORES",presentacion:"75 g",codigo:"1000193",marca:"",precioUnitario:3,habilitado:1},
// {nombre:"LB PORCION 3 SABORES",presentacion:"75 g",codigo:"1000194",marca:"",precioUnitario:3,habilitado:1},
// {nombre:"LB ALFAJOR",presentacion:"12 unidades",codigo:"1000195",marca:"",precioUnitario:18,habilitado:1},
// {nombre:"LB ALFAJOR",presentacion:"8 unidades",codigo:"1000196",marca:"",precioUnitario:12,habilitado:1},
// {nombre:"LB SUSPIROS",presentacion:"Unidad",codigo:"1000197",marca:"",precioUnitario:5,habilitado:1}]

// const postRequest = async function(item) {
//     try {
//         const response = await axios.post('http://46.183.113.134:3000/api/productos', item);       
//         console.log(response.data);
//     } catch (error) {
//         console.error(error);
//     }
// }

// productos.map(item => postRequest(item) )

