@apiTasks = http://localhost:3000/api/tasks
@apiVentas = http://localhost:3000/api/ventas
@apiProductos = http://localhost:3000/api/productos

### Get Tasks
GET {{apiVentas}}

### Ultima venta
GET {{apiVentas}}/ultimo

### Create a new Task
POST {{apiTasks}}
Content-Type: application/json

[
  {
    "title": "tarea 2",
    "description": "Hacer UNA api"
  }
]

### Consulta para productos

GET {{apiProductos}}?busquedaPorNombre=keito

### Crear un nuevo producto
POST http://46.183.113.134:3000/api/productos
Content-Type: application/json

  {
    "nombre": "DP Exportación",
    "presentacion": "1Kg", 
    "codigo": "1000004", 
    "marca": "Doña Pepa",
    "precioUnitario": 20,
    "habilitado": true
  }

### Create a new Vent
POST {{apiVentas}}
Content-Type: application/json

  { 
    "usuario": "Luis Vendedor",
    "serie": "E000",
    "numero":4,
    "lista" : [
      {
        "numLista": 1,
        "cod": 100192,
        "descripcion": "Turroncito",
        "unidades": "2 unidades",
        "cantidad":2,
        "descuento":10.5,
        "precioUnitario":25.6,
        "precioUnitarioIgv":3.5,
        "total":32.0
      }
    ],
    "tipoRegalo":"Probador",
    "CantidadRegalo":2,
    "tipoDocumentoCliente":"DNI",
    "numeroDocumentoCliente": 47313459,
    "fechaEmision":"",
    "nombreCliente": "Hans Comprador",
    "tipoMoneda":"Soles",
    "igv": 0.19 ,
    "mail": "luis@gmail.com",
    "celular": 986934174,
    "condicionPago": "Tarjeta",
    "numeroOperacion": "e3333",
    "provincia": "Lima",
    "canalVenta":"Whatsapp",
    "delivery":  true,
    "direccion":  "Mi casa",
    "referencias": "Al costado del vecino",
    "gravada": 400,
    "descuento": 10,
    "totalIgv": 50,
    "totalDelivery": 5.0,
    "totalPagar":520
  }

### Get Single Task
GET {{apiTasks}}/5fc500819bf75f1ffdc48da7

### Update
PUT {{apiTasks}}/5fc500819bf75f1ffdc48da7
Content-Type: application/json

{
  "title": "Title Updated",
  "description": "my updated description",
  "done": false
}

### Get Tasks and search
GET {{apiTasks}}?title=up

### Get all Done tasks
GET {{apiTasks}}/done

### DELETE Single Task
DELETE {{apiTasks}}/5fc500819bf75f1ffdc48da7

### DELETE all tasks
DELETE {{apiTasks}}